### ISSUE TITLE
[FEATURE] Breeding

### ISSUE THREAD

**Issue by TheOpossumPeople** [MrKacafirekCZ/doggo-mod-overhauled#25]
**Is your feature request related to a problem? Please describe.**
I can't seem to breed the dogs or find out how to try. Not sure if its glitch, on purpose, or I've failed to find the right method.

**Describe the solution you'd like**
Instructions on how to breed the dogs or the feature added.

**Describe alternatives you've considered**
I have tried various meats and the bone. 

**Additional context**
N/A

**Comment by MrKacafirekCZ** [comment]
Hello, breeding was already a problem before because of the new eating mechanic that I added. There used to be a temporary fix by having you, the player, give a dog 2 meats and the same goes for the other dog. Seems like I've since removed that fix and now there is no breeding mechanic as far as I can tell.

So the current issue then is that the vanilla breeding mechanic now overlaps with the new eating mechanic. May I ask, if you've thought about a way or perhaps if you have an idea for a solution for the breeding mechanic to work alongside the eating mechanic?

**Comment by TheOpossumPeople** [comment]
I know nothing about modding-- would using splash potion or leaving off the mechanic for one particular food/item be feasible? The eating mechanic is very cute. For my particular playing style I do need breeding, but I will be checking frequently to see if there was a work around :)

**Comment by TheOpossumPeople** [comment]
I really like that idea, especially with breeding taking the extra step of sneaking so its easy to just go around feeding the doggos without accidental puppies, but still simple to breed them when wanted.

**Comment by MrKacafirekCZ** [comment]
This feature will be added in the next version!
